name: feiding
server: 
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
    
spring:
  #profiles: dev
  datasource: 
    url: jdbc:mysql://localhost:3306/xf?serverTimezone=GMT%2B8
    #url: jdbc:mysql://144.34.215.43:7777/xf?serverTimezone=GMT%2B8
    username: root
    password: root
    #password: jinghua1.DB
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    refresh-mapper: true
    configuration:
      cache-enabled: false
